local rank={
    [1]={
        name="总战力榜",        
        id=1,
        type=1
    }
    ,[2]={
        name="英雄榜",        
        id=2,
        type=3
    }
    ,[3]={
        name="公会榜",        
        id=3,
        type=0
    }
    ,[4]={
        name="最强战力榜",        
        id=4,
        type=2
    }
    ,[5]={
        name="疆土榜",        
        id=5,
        type=4
    }
    ,[6]={
        name="公会排位榜",        
        id=6,
        type=0
    }
}
return rank;