----公会战消息----
--author:hhh time:2017.11.6
UWNN={
	UWInitCmd="UWInitCmd",--初始化
	UWRankCmd="UWRankCmd",--排行
	UWRewardCmd="UWRewardCmd",--累计奖励
	UWDefendCmd="UWDefendCmd",--守卫
	UWDiaoBingCmd="UWDiaoBingCmd",--调兵
	UWJiaoZhenCmd="UWJiaoZhenCmd",--叫阵
	UWShouBingCmd="UWShouBingCmd",--收兵
	UWChuBingCmd="UWChuBingCmd",--出兵
	UWTeamInfoCmd="UWTeamInfoCmd",--队伍信息
	UWNTFCmd="UWNTFCmd",--后台推送
	UWSelectCampCmd="UWSelectCampCmd",--选择阵营
	UWExitCmd="UWExitCmd",--退出公会战
	UWFightDetailCmd="UWFightDetailCmd",--战斗详情
	UWMyKillRankCmd="UWMyKillRankCmd",--我的杀敌排名
	
	UWInitProxy="UWInitProxy",
	UWInitProxyInit="UWInitProxyInit",--初始化
	UWInitProxyOpenRank="UWInitProxyOpenRank",--杀敌排行榜
	UWInitProxyOpenReward="UWInitProxyOpenReward",--累计奖励
	UWInitProxyOpenJiaoZhen="UWInitProxyOpenJiaoZhen",--叫阵
	UWInitProxyOpenDiaoBin="UWInitProxyOpenDiaoBin",--调兵
	UWInitProxyOpenTeamInfo="UWInitProxyOpenTeamInfo",--队伍信息
	UWInitProxyOpenSelectCamp="UWInitProxyOpenSelectCamp",--选择阵营
	UWInitProxyOpenCallDefend="UWInitProxyOpenCallDefend",--招募守卫
	UWInitProxyUpdateJiaoZhen="UWInitProxyUpdateJiaoZhen",--战斗结果
	UWInitProxyFightAction="UWInitProxyFightAction",--消息推送战斗
	UWInitProxyFightBack="UWInitProxyFightBack",--公会战兵线收兵
	UWInitProxyFightResult="UWInitProxyFightResult",--战斗结果
	UWInitProxyArmyNum="UWInitProxyArmyNum",--军队数量改变
	UWInitProxyUpdataDiaoBin="UWInitProxyUpdataDiaoBin",--调兵成功刷新数据
	UWInitProxyHeadNum="UWInitProxyHeadNum",--调兵成功刷新数据
	UWInitProxyWillOver="UWInitProxyWillOver",--战斗即将结束
	UWInitProxyKillNum="UWInitProxyKillNum",--杀敌数量改变
	
	UWTopView="UWTopView",
	UWMidView="UWMidView",
	UWBtmView="UWBtmView"
}